# Generated by Django 6.0.7 on 2026-07-26 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_display_name', models.CharField(default='RAHMA Islamic Foundation & Charity', max_length=255)),
                ('bank_name', models.CharField(blank=True, default='State Bank of India', max_length=255)),
                ('account_holder_name', models.CharField(blank=True, default='RAHMA Charitable Trust', max_length=255)),
                ('account_number', models.CharField(blank=True, default='9876543210123', max_length=100)),
                ('ifsc_code', models.CharField(blank=True, default='SBIN0001234', max_length=20)),
                ('upi_id', models.CharField(blank=True, default='rahma.trust@sbi', max_length=100)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='payment_qrs/')),
                ('payment_gateway', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('CASHFREE', 'Cashfree'), ('PHONEPE', 'PhonePe')], default='RAZORPAY', max_length=50)),
                ('api_key', models.CharField(blank=True, default='rzp_test_rahma12345678', max_length=255)),
                ('secret_key', models.CharField(blank=True, default='rahma_secret_key_987654321', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, default='whsec_rahma_webhook_secret_key', max_length=255)),
                ('is_test_mode', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_setting', to='organizations.organization')),
            ],
        ),
    ]
