# Generated by Django 6.0.7 on 2026-07-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('tagline', models.CharField(blank=True, default='Empowering Communities & Charitable Causes', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/')),
                ('hero_banner', models.ImageField(blank=True, null=True, upload_to='organizations/banners/')),
                ('about_text', models.TextField(blank=True, default='RAHMA is a dedicated platform facilitating transparent online donations for mosques, madrasas, and charitable organizations.')),
                ('address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
