# Generated by Django 6.0.7 on 2026-07-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='house_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='madrasa_name',
            field=models.CharField(default='Other', max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='other_place',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_phone',
            field=models.CharField(max_length=20),
        ),
    ]
